# yaml
services:
  app:
    build: .
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/yourdb
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}
